### ISSUE TITLE
Feedback on progress of the import 

### ISSUE THREAD

**Issue by gregoriopellegrino** [andrewdodd/django-nsync#13]
Hi,
I have some big imports to do (programmatically) and it would be very useful to have a function that gives the feedback on progress of the import.

Is there something that can help me?

Gregorio

**Comment by andrewdodd** [comment]
Hi Gregorio,

Sorry I don't really use this library very much anymore, but I'm glad that someone is!

It might be worth you implementing your own policy? One that is similar the ones in the policies.py module? Maybe something like this:

    class NotifyStepsPolicy:
        def __init__(self, actions, callback):
            self.actions = actions
            self.callback = callback

        def execute(self):
            for action in self.actions:
                action.execute()
                self.callback(action)
