### ISSUE TITLE
Import files programmatically

### ISSUE THREAD

**Issue by gregoriopellegrino** [andrewdodd/django-nsync#7]
Can't find in te documentation how to import files programmatically.

**Comment by andrewdodd** [comment]
Hi @gregoriopellegrino ,

I'm not quite sure what you mean. How do you want to import the files?

**Comment by gregoriopellegrino** [comment]
I mean importing the file using a python script and not the command line, so I can automate the import after the upload of the CSV file

**Comment by andrewdodd** [comment]
You could try and execute the command from your script via `call_command`. See [here](https://docs.djangoproject.com/en/1.9/ref/django-admin/#django.core.management.call_command)

Or, you could do something similar to the code in one of the Nsync command files, e.g. [here](https://github.com/andrewdodd/django-nsync/blob/master/src/nsync/management/commands/syncfile.py)

**Comment by gregoriopellegrino** [comment]
Ok, I'll copy the code from Nsync command files.

Thank you
