### ISSUE TITLE
'' value has an invalid date format. It must be in YYYY-MM-DD format.

### ISSUE THREAD

**Issue by gregoriopellegrino** [andrewdodd/django-nsync#9]
The field is set as not mandatory:
`PubDate = models.DateField(blank=True, null=True)`

But when I try to import a row with an empty cell I get the error:
`'' value has an invalid date format. It must be in YYYY-MM-DD format.`

**Comment by andrewdodd** [comment]
Yep, definitely an issue. I'll see what I can do.

**Comment by andrewdodd** [comment]
Hey,

Sorry for the delay in this. I've been away.

I've submitted a change that I think fixes this at https://github.com/andrewdodd/django-nsync/commit/df23d10228d4d07d44546ff2e6a752f47a8240e4
